# .github/workflows/deploy.yml
name: Deploy UTA PWYW App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run basic test
        run: |
          python -c "import flask, stripe, gspread"

      - name: Deploy to production
        run: echo "Deployment logic goes here (e.g. SCP to EC2, push to Vercel, etc.)"
